<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $schools = [
            'A.T. Still University of Health Sciences (AZ / MO)',
            'Abilene Christian University (TX)',
            'Abraham Baldwin Agricultural College (GA)',
            'Academy of Art University (CA)',
            'Adams State College (CO)',
            'Adelphi University (NY)',
            'Adler Graduate School (MN)',
            'Adler University (IL)',
            'Adrian College (MI)',
            'Adventist University of Health Sciences (FL)',
            'Agnes Scott College (GA)',
            'AIB College of Business (IA)',
            'Air Force Institute of Technology (OH)',
            'Air University (AL)',
            'Alabama A&M University (AL)',
            'Alabama State University (AL)',
            'Alaska Bible College (AK)',
            'Alaska Pacific University (AK)',
            'Albany College of Pharmacy & Health Sciences (NY)',
            'Albany Medical College (NY)',
            'Albany State University (GA)',
            'Albertus Magnus College (CT)',
            'Albion College (MI)',
            'Albright College (PA)',
            'Alcorn State University (MS)',
            'Alderson-Broaddus College (WV)',
            'Alfred University (NY)',
            'Alice Lloyd College (KY)',
            'Allegheny College (PA)',
            'Allen College (IA)',
            'Allen University (SC)',
            'Alliant International University (CA)',
            'Alma College (MI)',
            'Alvernia University (PA)',
            'Alverno College (WI)',
            'Ambassador University (TX) (closed spring 1997)',
            'Amberton University (TX)',
            'American Academy of Art (IL)',
            'American College of Acupuncture & Oriental Medicine (TX)',
            'American College of Education (IL)',
            'The American College of Financial Services (PA)',
            'American Conservatory Theater (CA)',
            'American Film Institute (CA)',
            'American Indian College of the Assemblies of God (AZ)',
            'American InterContinental University (IL)',
            'American International College (MA)',
            'American Jewish University (CA)',
            'American Military University (WV)',
            'American Public University (WV)',
            'American University (DC)',
            'American University of Puerto Rico (PR)',
            'Amherst College (MA)',
            'Amridge University (AL)',
            'Anabaptist Mennonite Biblical Seminary (IN)',
            'Anderson University (SC)',
            'Anderson University (IN)',
            'Andover Newton Theological School (MA)',
            'Andrews University (MI)',
            'Angelo State University (TX)',
            'Anna Maria College (MA)',
            'Antioch College (OH)',
            'Antioch University–Midwest (OH)',
            'Antioch University–New England (NH)',
            'Antioch University–Los Angeles (CA)',
            'Antioch University–Santa Barbara (CA)',
            'Antioch University–Seattle (WA)',
            'AOMA Graduate School of Integrative Medicine (TX)',
            'Appalachian Bible College (WV)',
            'Appalachian State University (NC)',
            'Aquinas College (MI)',
            'Aquinas College (TN)',
            'Aquinas Institute of Theology (MO)',
            'Arcadia University (PA)',
            'Argosy University (IL)',
            'Arizona Christian University (AZ)',
            'Arizona State University (AZ)',
            'Arizona State University–Downtown Phoenix Campus (AZ)',
            'Arizona State–Polytechnic Campus (AZ)',
            'Arizona State University–West Campus (AZ)',
            'Arkansas Baptist College (AR)',
            'Arkansas State University (AR)',
            'Arkansas Tech University (AR)',
            'Arlington Baptist College (TX)',
            'Armstrong State University (GA)',
            'Art Academy of Cincinnati (OH)',
            'Art Center College of Design (CA)',
            'Art Institute of Atlanta (GA)',
            'Art Institute of Colorado (CO)',
            'Art Institute of Dallas (TX)',
            'Art Institute of Houston (TX)',
            'Art Institute of Pittsburgh (PA)',
            'Art Institute of Portland (OR)',
            'Art Institute of Seattle (WA)',
            'Asbury Theological Seminary (KY)',
            'Asbury University (KY)',
            'Ashford University (CA/IA)',
            'Ashland University (OH)',
            'Assumption College (MA)',
            'Athenaeum of Ohio (OH)',
            'Athens State University (AL)',
            'Auburn University (AL)',
            'Auburn University at Montgomery (AL)',
            'Augsburg College (MN)',
            'Augustana College (IL)',
            'Augustana College (SD)',
            'Aurora University (IL)',
            'Austin College (TX)',
            'Austin Graduate School of Theology (TX)',
            'Austin Peay State University (TN)',
            'Austin Presbyterian Theological Seminary (TX)',
            'Ave Maria University (FL)',
            'Averett University (VA)',
            'Avila University (MO)',
            'Azusa Pacific University (CA)',
            'Babson College (MA)',
            'Bacone College (OK)',
            'Baldwin-Wallace University (OH)',
            'Ball State University (IN)',
            'Baker College (MI)',
            'Baker University (KS)',
            'Bangor Theological Seminary (ME) (closed 22 June 2013)',
            'Bank Street College of Education (NY)',
            'Baptist Bible College (MO)',
            'The Baptist College of Florida (FL)',
            'Baptist Memorial College of Health Sciences (TN)',
            'Baptist Missionary Association Theological Seminary (TX)',
            'Barclay College (KS)',
            'Bard College (NY)',
            'Bard College at Simons Rock (MA)',
            'Barnard College (NY)',
            'Barry University (FL)',
            'Barton College (NC)',
            'Bastyr University (WA)',
            'Bates College (ME)',
            'Bauder College (GA) (closing December 2015)',
            'Bay Path University (MA)',
            'Bay State College (MA)',
            'Baylor College of Medicine (TX)',
            'Baylor University (TX)',
            'Beacon College (FL)',
            'Becker College (MA)',
            'Belhaven University (MS)',
            'Bellarmine University (KY)',
            'Bellevue College (WA)',
            'Bellevue University (NE)',
            'Bellin College (WI)',
            'Belmont University (TN)',
            'Belmont Abbey College (NC)',
            'Beloit College (WI)',
            'Bemidji State University (MN)',
            'Benedict College (SC)',
            'Benedictine College (KS)',
            'Benedictine University (IL)',
            'Benjamin Franklin Institute of Technology (MA)',
            'Bennett College (NC)',
            'Bennington College (VT)',
            'Bentley University (MA)',
            'Berea College (KY)',
            'Berkeley College (NJ)',
            'Berklee College of Music (MA)',
            'Berry College (GA)',
            'Bethany College (KS)',
            'Bethany College (WV)',
            'Bethany Lutheran College (MN)',
            'Bethany Theological Seminary (IN)',
            'Bethel College (IN)',
            'Bethel College (KS)',
            'Bethel University & Seminary (MN)',
            'Bethel University (TN)',
            'Bethesda University of California (CA)',
            'Bethune-Cookman University (FL)',
            'Beulah Heights University (GA)',
            'Biblical Theological Seminary (PA)',
            'Biola University (CA)',
            'Birmingham-Southern College (AL)',
            'Bismark State College (ND)',
            'Black Hills State University (SD)',
            'Blackburn College (IL)',
            'Blessing-Rieman College of Nursing (IL)',
            'Bloomfield College (NJ)',
            'Bloomsburg University of Pennsylvania (PA)',
            'Blue Mountain College (MS)',
            'Bluefield College (VA)',
            'Bluefield State College (WV)',
            'Bluffton University (OH)',
            'Boise State University (ID)',
            'Boricua College (NY)',
            'Boston Architectural College (MA)',
            'Boston College (MA)',
            'Boston Conservatory (MA)',
            'Boston Graduate School of Psychoanalysis (MA)',
            'Boston University (MA)',
            'Bowdoin College (ME)',
            'Bowie State University (MD)',
            'Bowling Green State University (OH)',
            'Bradley University (IL)',
            'Brandeis University (MA)',
            'Brandman University (CA)',
            'Brenau University (GA)',
            'Brescia University (KY)',
            'Brevard College (NC)',
            'Brewton-Parker College (GA)',
            'Briar Cliff University (IA)',
            'Briarcliffe College (NY)',
            'Bridgewater College (VA)',
            'Bridgewater State University (MA)',
            'Brigham Young University (UT)',
            'Brigham Young University–Hawaii (HI)',
            'Brigham Young University–Idaho (ID)',
            'Brite Divinity School (TX)',
            'Broward College (FL)',
            'Brown University (RI)',
            'Bryan College (TN)',
            'Bryan College of Health Sciences (NE)',
            'Bryant University (RI)',
            'Bryn Athyn College (PA)',
            'Bryn Mawr College (PA)',
            'Bucknell University (PA)',
            'Buena Vista University (IA)',
            'Burlington College (VT)',
            'Butler University (IN)',
            'Cabarrus College of Health Sciences (NC)',
            'Cabrini College (PA)',
            'Cairn University (PA)',
            'Caldwell University (NJ)',
            'California Baptist University (CA)',
            'California College of the Arts (CA)',
            'California Institute of the Arts (CA)',
            'California Institute of Integral Studies (CA)',
            'California Institute of Technology (CA)',
            'California Lutheran University (CA)',
            'California Maritime Academy (CA)',
            'California Northstate University (CA)',
            'California Polytechnic State University, San Luis Obispo (CA)',
            'California State Polytechnic University, Pomona (CA)',
            'California State University–Bakersfield (CA)',
            'California State University–Channel Islands (CA)',
            'California State University–Chico (CA)',
            'California State University–Dominguez Hills (CA)',
            'California State University–East Bay (CA)',
            'California State University–Fresno (CA)',
            'California State University–Fullerton (CA)',
            'California State University–Long Beach (CA)',
            'California State University–Los Angeles (CA)',
            'California State University–Monterey Bay (CA)',
            'California State University–Northridge (CA)',
            'California State University–Sacramento (CA)',
            'California State University–San Bernardino (CA)',
            'California State University–San Marcos (CA)',
            'California State University–Stanislaus (CA)',
            'California State University System (CA)',
            'California University of Pennsylvania (PA)',
            'Calumet College of Saint Joseph (IN)',
            'Calvary Baptist Seminary (PA)',
            'Calvary Bible College & Theological Seminary (MO)',
            'Calvin College (MI)',
            'Cambridge College (MA)',
            'Cameron University (OK)',
            'Campbell University (NC)',
            'Campbellsville University (KY)',
            'Canisius College (NY)',
            'Capella University (MN)',
            'Capital University (OH)',
            'Capitol Technology University (MD)',
            'Cardinal Stritch University (WI)',
            'Caribbean University (PR)',
            'Carleton College (MN)',
            'Carlos Albizu University (PR)',
            'Carlos Albizu University–Miami Campus (FL)',
            'Carlow University (PA)',
            'Carnegie Mellon University (PA)',
            'Carroll College (MT)',
            'Carroll University (WI)',
            'Carson-Newman University (TN)',
            'Carthage College (WI)',
            'Case Western Reserve University (OH)',
            'Castleton State College (VT)',
            'Catawba College (NC)',
            'Catholic Theological Union (IL)',
            'The Catholic University of America (DC)',
            'Cazenovia College (NY)',
            'Cedar Crest College (PA)',
            'Cedarville University (OH)',
            'Centenary College (NJ)',
            'Centenary College of Louisiana (LA)',
            'Central Baptist College (AR)',
            'Central Baptist Theological Seminary (KS)',
            'Central Christian College of Kansas (KS)',
            'Central Christian College of the Bible (MO)',
            'Central College (IA)',
            'Central Connecticut State University (CT)',
            'Central Methodist University (MO)',
            'Central Michigan University (MI)',
            'Central Penn College (PA)',
            'Central State University (OH)',
            'Central Washington University (WA)',
            'Centre College (KY)',
            'Centro de Estudios Avanzados de Puerto Rico y el Caribe (PR)',
            'Chadron State College (NE)',
            'Chamberlain College of Nursing (IL)',
            'Chaminade University (HI)',
            'Champlain College (VT)',
            'Chancellor University (OH) (closed 25 August 2013)',
            'Chapman University (CA)',
            'Charles R. Drew University of Medicine & Science (CA)',
            'Charleston Southern University (SC)',
            'Charter Oak State College (CT)',
            'Bryn Athyn College (PA)',
            'Chestnut Hill College (PA)',
            'Cheyney University (PA)',
            'The Chicago School of Professional Psychology (IL)',
            'Chicago State University (IL)',
            'Chicago Theological Seminary (IL)',
            'Chipola College (FL)',
            'Chowan University (NC)',
            'Christ the King Seminary (NY)',
            'Christendom College (VA)',
            'Christian Brothers University (TN)',
            'Christian Theological Seminary (IN)',
            'Christopher Newport University (VA)',
            'Church Divinity School of the Pacific (CA)',
            'Cincinnati Christian University (OH)',
            'Cincinnati College of Mortuary Science',
            'The Citadel (SC)',
            'City University of Seattle (WA)',
            'City University of New York (NY)',
            'Claflin University (SC)',
            'Claremont Consortium of Colleges (CA)',
            'Claremont School of Theology (CA)',
            'Clarion University of Pennsylvania (PA)',
            'Clark University (MA)',
            'Clark Atlanta University (GA)',
            'Clarke University (IA)',
            'Clarkson College (NE)',
            'Clarkson University (NY)',
            'Clayton State University (GA)',
            'Clear Creek Baptist Bible College (KY)',
            'Clearwater Christian College (FL) (closed 05 June 2015)',
            'Cleary University (MI)',
            'Clemson University (SC)',
            'Cleveland Chiropractic College (KS)',
            'Cleveland Institute of Art (OH)',
            'Cleveland Institute of Music (OH)',
            'Cleveland State University (OH)',
            'Coastal Carolina University (SC)',
            'Coe College (IA)',
            'Cogswell Polytechnical College (CA)',
            'Coker College (SC)',
            'Colby College (ME)',
            'Colby-Sawyer College (NH)',
            'Colegio Universitario de San Juan (PR)',
            'Colgate University (NY)',
            'College for Creative Studies (MI)',
            'College for Financial Planning (CO)',
            'College of the Atlantic (ME)',
            'College of Biblical Studies–Houston (TX)',
            'College of Central Florida (FL)',
            'College of Charleston (SC)',
            'College of Coastal Georgia (GA)',
            'College of the Holy Cross (MA)',
            'The College of Idaho (ID)',
            'College of the Menominee Nation (WI)',
            'College of Mount Saint Joseph (OH)',
            'College of Mount Saint Vincent (NY)',
            'The College of New Jersey (NJ)',
            'College of New Rochelle (NY)',
            'College of the Ozarks (MO)',
            'College of Saint Benedict & Saint Johns University (MN)',
            'College of Saint Elizabeth (NJ)',
            'College of Saint Rose (NY)',
            'College of Saint Joseph (VT)',
            'College of Saint Mary (NE)',
            'College of Saint Scholastica (MN)',
            'College of Southern Nevada (NV)',
            'College of William and Mary (VA)',
            'College of Wooster (OH)',
            'Colorado Christian University (CO)',
            'Colorado College (CO)',
            'Colorado Mesa University (CO)',
            'Colorado School of Mines (CO)',
            'Colorado State University (CO)',
            'Colorado State University–Pueblo (CO)',
            'Colorado Technical University (CO)',
            'Columbia Centro Universitario (PR)',
            'Columbia College (MO)',
            'Columbia College (SC)',
            'Columbia College Chicago (IL)',
            'Columbia College Hollywood (CA)',
            'Columbia College of Nursing (WI)',
            'Columbia International University (SC)',
            'Columbia Theological Seminary (GA)',
            'Columbia University (NY)',
            'Columbus College of Art & Design (OH)',
            'Columbus State University (GA)',
            'Conception Seminary College (MO)',
            'Concord University (WV)',
            'Concordia College–Alabama (AL)',
            'Concordia College–Bronxville (NY)',
            'Concordia College–Moorhead (MN)',
            'Concordia College–New York (NY)',
            'Concordia Seminary–Saint Louis (MO)',
            'Concordia Theological Seminary (IN)',
            'Concordia University–Ann Arbor (MI)',
            'Concordia University–Chicago (IL)',
            'Concordia University–Irvine (CA)',
            'Concordia University–Nebraska (NE)',
            'Concordia University–Portland (OR)',
            'Concordia University–Saint Paul (MN)',
            'Concordia University–Texas (TX)',
            'Concordia University–Wisconsin (WI)',
            'Connecticut College (CT)',
            'Conservatorio de Música de Puerto Rico (PR)',
            'Converse College (SC)',
            'Conway School of Landscape Design (MA)',
            'The Cooper Union for the Advancement of Science & Art (NY)',
            'Coppin State University (MD)',
            'Corban University (OR)',
            'Cornell College (IA)',
            'Cornell University (NY)',
            'Cornerstone University (MI)',
            'Cornish College of the Arts (WA)',
            'Cottey College (MO)',
            'Covenant College (GA)',
            'Covenant Theological Seminary (MO)',
            'Cox College (MO)',
            'Cranbrook Academy of Art (MI)',
            'Creighton University (NE)',
            'Criswell College (TX)',
            'Crossroads College (MN)',
            'Crowleys Ridge College (AR)',
            'Crown College (MN)',
            'Culinary Institute of America (NY)',
            'Culver-Stockton College (MO)',
            'Cumberland University (TN)',
            'Curry College (MA)',
            'Curtis Institute of Music (PA)',
            'Daemen College (NY)',
            'Dakota State University (SD)',
            'Dakota Wesleyan University (SD)',
            'Dallas Baptist University (TX)',
            'Dallas Christian College (TX)',
            'Dallas Theological Seminary (TX)',
            'Dalton State College (GA)',
            'Daniel Webster College (NH)',
            'Dartmouth College (NH)',
            'Davenport University (MI)',
            'Davidson College (NC)',
            'Davis College (NY)',
            'Davis & Elkins College (WV)',
            'Daytona State College (FL)',
            'Dean College (MA)',
            'Defiance College (OH)',
            'Delaware State University (DE)',
            'Delaware Valley College (PA)',
            'Delta State University (MS)',
            'Denison University (OH)',
            'Denver Seminary (CO)',
            'DePaul University (IL)',
            'DePauw University (IN)',
            'Des Moines University–Osteopathic Medical Center (IA)',
            'DeSales University (PA)',
            'DeVry University (IL)',
            'DeVry University–Addison (IL)',
            'DeVry University–Arlington (VA)',
            'DeVry University–Chicago (IL)',
            'DeVry University–Georgia (GA)',
            'DeVry University–Irving (TX)',
            'DeVry University–Kansas City (MO)',
            'DeVry University–Long Beach (CA)',
            'DeVry University–Orlando (FL)',
            'DeVry University–Phoenix (AZ)',
            'DeVry University–Pomona (CA)',
            'Dickinson College (PA)',
            'Dickinson State University (ND)',
            'Dillard University (LA)',
            'Divine Word College (IA)',
            'Dixie State University (UT)',
            'Doane College (NE)',
            'Dominican College (NY)',
            'Dominican House of Studies (DC)',
            'Dominican School of Philosophy & Theology (CA)',
            'Dominican University (IL)',
            'Dominican University of California (CA)',
            'Donnelly College (KS)',
            'Dordt College (IA)',
            'Dowling College (NY)',
            'Drake University (IA)',
            'Drew University (NJ)',
            'Drexel University (PA)',
            'Drury University (MO)',
            'Duke University (NC)',
            'Dunwoody College of Technology (MN)',
            'Duquesne University (PA)',
            'D´Youville College (NY)',
            'Earlham College (IN)',
            'East Carolina University (NC)',
            'East Central University (OK)',
            'East Stroudsburg State University of Pennsylvania (PA)',
            'East Tennessee State University (TN)',
            'East Texas Baptist University (TX)',
            'East-West University (IL)',
            'Eastern Connecticut State University (CT)',
            'Eastern Florida State College (FL)',
            'Eastern Illinois University (IL)',
            'Eastern Kentucky University (KY)',
            'Eastern Mennonite University (VA)',
            'Eastern Michigan University (MI)',
            'Eastern Nazarene College (MA)',
            'Eastern New Mexico University (NM)',
            'Eastern Oregon University (OR)',
            'Eastern University (PA)',
            'Eastern Virginia Medical School (VA)',
            'Eastern Washington University (WA)',
            'Eckerd College (FL)',
            'ECPI University (VA)',
            'Eden Theological Seminary (MO)',
            'Edgewood College (WI)',
            'Edinboro University of Pennsylvania (PA)',
            'EDP College (PR)',
            'Edward Waters College (FL)',
            'Elizabeth City State University (NC)',
            'Elizabethtown College (PA)',
            'Elmhurst College (IL)',
            'Elmira College (NY)',
            'Elms College (MA)',
            'Elon University (NC)',
            'Embry-Riddle Aeronautical University (AZ / FL)',
            'Emerson College (MA)',
            'Emmanuel Christian Seminary (TN)',
            'Emmanuel College (GA)',
            'Emmanuel College (MA)',
            'Emmaus Bible College (IA)',
            'Emporia State University (KS)',
            'Emory & Henry College (VA)',
            'Emory University (GA)',
            'Endicott College (MA)',
            'Erikson Institute (IL)',
            'Erskine College (SC)',
            'Escuela de Artes Plásticas de Puerto Rico (PR)',
            'Eureka College (IL)',
            'Evangel University (MO)',
            'Evangelical Theological Seminary (PA)',
            'Everglades University (FL)',
            'Evergreen State College (WA)',
            'Excelsior College (NY)',
            'Fairfield University (CT)',
            'Fairleigh Dickinson University (NJ)',
            'Fairmont State University (WV)',
            'Faith Baptist Bible College & Theological Seminary (IA)',
            'Fashion Institute of Design & Merchandising (CA)',
            'Faulkner University (AL)',
            'Fayetteville State University (NC)',
            'Felician College (NJ)',
            'Ferris State University (MI)',
            'Ferrum College (VA)',
            'Fielding Graduate University (CA)',
            'Finlandia University (MI)',
            'Fisher College (MA)',
            'Fisk University (TN)',
            'Fitchburg State University (MA)',
            'Five Towns College (NY)',
            'Flagler College (FL)',
            'Florida Agricultural & Mechanical University (FL)',
            'Florida Atlantic University (FL)',
            'Florida College (FL)',
            'Florida Gateway College (FL)',
            'Florida Gulf Coast University (FL)',
            'Florida Institute of Technology (FL)',
            'Florida International University (FL)',
            'Florida Memorial University (FL)',
            'Florida National University (FL)',
            'Florida Southern College (FL)',
            'Florida SouthWestern State College (FL)',
            'Florida State College at Jacksonville (FL)',
            'Florida State University (FL)',
            'Fontbonne University (MO)',
            'Fordham University (NY)',
            'Forest Institute of Professional Psychology (MO)',
            'Fort Hays State University (KS)',
            'Fort Lewis College (CO)',
            'Fort Valley State University (GA)',
            'Framingham State University (MA)',
            'Francis Marion University (SC)',
            'Franciscan School of Theology (CA)',
            'Franciscan University of Steubenville (OH)',
            'Frank Lloyd Wright School of Architecture (AZ)',
            'Franklin & Marshall College (PA)',
            'Franklin College (IN)',
            'Franklin Pierce University (NH)',
            'Franklin University (OH)',
            'Franklin W. Olin College of Engineering (MA)',
            'Freed-Hardeman University (TN)',
            'Fresno Pacific University (CA)',
            'Friends University (KS)',
            'Frontier Nursing University (KY)',
            'Frostburg State University (MD)',
            'Fuller Theological Seminary (CA)',
            'Furman University (SC)',
            'Future Generations Graduate School (WV)',
            'Gallaudet University (DC)',
            'Gannon University (PA)',
            'Gardner-Webb University (NC)',
            'Garrett-Evangelical Theological Seminary (IL)',
            'Geneva College (PA)',
            'George Fox University (OR)',
            'George Mason University (VA)',
            'George Washington University (DC)',
            'George Washington University–Virginia Science & Technology Campus (VA)',
            'Georgetown College (KY)',
            'Georgetown University (DC)',
            'Georgia College & State University (GA)',
            'Georgia Gwinnett College (GA)',
            'Georgia Institute of Technology (GA)',
            'Georgia Regents University (GA)',
            'Georgia Southern University (GA)',
            'Georgia Southwestern State University (GA)',
            'Georgia State University (GA)',
            'Georgian Court University (NJ)',
            'Gettysburg College (PA)',
            'Glenville State College (WV)',
            'Global University (MO)',
            'Gods Bible School & College (OH)',
            'Goddard College (VT)',
            'Golden Gate Baptist Theological Seminary (CA)',
            'Golden Gate University (CA)',
            'Goldey-Beacom College (DE)',
            'Goldfarb School of Nursing at Barnes-Jewish College (MO)',
            'Gonzaga University (WA)',
            'Goodwin College (CT)',
            'Gordon State College (GA)',
            'Gordon College (MA)',
            'Gordon-Conwell Theological Seminary (MA)',
            'Goshen College (IN)',
            'Goucher College (MD)',
            'Governors State University (IL)',
            'Grace Bible College (MI)',
            'Grace College & Seminary (IN)',
            'Grace University (NE)',
            'Graceland University (IA)',
            'Graduate Institute of Applied Linguistics (TX)',
            'Graduate Theological Union (CA)',
            'Grambling State University (LA)',
            'Grand Canyon University (AZ)',
            'Grand Valley State University (MI)',
            'Grand View University (IA)',
            'Granite State College (NH)',
            'Gratz College (PA)',
            'Great Basin College (NV)',
            'Great Lakes Christian College (MI)',
            'Green Mountain College (VT)',
            'Greensboro College (NC)',
            'Greenville College (IL)',
            'Grinnell College (IA)',
            'Grove City College (PA)',
            'Guilford College (NC)',
            'Gulf Coast State College (FL)',
            'Gustavus Adolphus College (MN)',
            'Gwynedd Mercy University (PA)',
            'Hamilton College (NY)',
            'Hamline University (MN)',
            'Hampden-Sydney College (VA)',
            'Hampshire College (MA)',
            'Hampton University (VA)',
            'Hannibal-Lagrange College (MO)',
            'Hanover College (IN)',
            'Hardin-Simmons University (TX)',
            'Harding University (AR)',
            'Harrington College of Design (IL)',
            'Harris-Stowe State University (MO)',
            'Harrisburg University of Science & Technology (PA)',
            'Hartford Seminary (CT)',
            'Hartwick College (NY)',
            'Harvard University (MA)',
            'Haskell Indian Nations University (KS)',
            'Hastings College (NE)',
            'Haverford College (PA)',
            'Hawaii Pacific University (HI)',
            'Hazelden Graduate School of Addiction Studies (MN)',
            'Hebrew College (MA)',
            'Hebrew Theological College (IL)',
            'Hebrew Union College–Jewish Institute of Religion (CA / OH / NY)',
            'Heidelberg University (OH)',
            'Hellenic College/Holy Cross Greek Orthodox School of Theology (MA)',
            'Henderson State University (AR)',
            'Hendrix College (AR)',
            'Heritage University (WA)',
            'Herzing University (WI)',
            'High Point University (NC)',
            'Hilbert College (NY)',
            'Hillsdale College (MI)',
            'Hiram College (OH)',
            'Hobart & William Smith Colleges (NY)',
            'Hobe Sound Bible College (FL)',
            'Hodges University (FL)',
            'Hofstra University (NY)',
            'Hollins University (VA)',
            'Holy Apostles College & Seminary (CT)',
            'Holy Cross College (IN)',
            'Holy Family University (PA)',
            'Holy Names University (CA)',
            'Hood College (MD)',
            'Hope College (MI)',
            'Hope International University (CA)',
            'Houghton College (NY)',
            'Houston Baptist University (TX)',
            'Howard Payne University (TX)',
            'Howard University (DC)',
            'Hult International Business School (MA)',
            'Humboldt State University (CA)',
            'Humphreys College (CA)',
            'Huntingdon College (AL)',
            'Huntington University (IN)',
            'Husson University (ME)',
            'Huston-Tillotson University (TX)',
            'Icahn School of Medicine at Mount Sinai (NY)',
            'Idaho State University (ID)',
            'Iliff School of Theology (CO)',
            'Illinois College (IL)',
            'Illinois College of Optometry (IL)',
            'Illinois Institute of Art (IL)',
            'Illinois Institute of Art–Schaumburg (IL)',
            'Illinois Institute of Technology (IL)',
            'Illinois State University (IL)',
            'Illinois Wesleyan University (IL)',
            'Immaculata University (PA)',
            'Indian River State College (FL)',
            'Indiana Institute of Technology (IN)',
            'Indiana State University (IN)',
            'Indiana University–Bloomington (IN)',
            'Indiana University–East (IN)',
            'Indiana University–Kokomo (IN)',
            'Indiana University–Northwest (IN)',
            'Indiana University–South Bend (IN)',
            'Indiana University–Southeast (IN)',
            'Indiana University System (IN)',
            'Indiana University/Purdue University at Columbus (IN)',
            'Indiana University/Purdue University at Fort Wayne (IN)',
            'Indiana University/Purdue University at Indianapolis (IN)',
            'Indiana University of Pennsylvania (PA)',
            'Indiana Wesleyan University (IN)',
            'Institute for Clinical Social Work (IL)',
            'Institute for the Psychological Sciences (VA)',
            'Institute of American Indian Arts (NM)',
            'Institute of World Politics (DC)',
            'Interdenominational Theological Center (GA)',
            'Iona College (NY)',
            'Iowa State University (IA)',
            'Iowa Wesleyan University (IA)',
            'Irell & Manella Graduate School of Biological Sciences (CA)',
            'Ithaca College (NY)',
            'Jackson State University (MS)',
            'Jacksonville University (FL)',
            'Jacksonville State University (AL)',
            'James Madison University (VA)',
            'Jarvis Christian College (TX)',
            'Jefferson College of Health Sciences (VA)',
            'The Jewish Theological Seminary of America (NY)',
            'John Brown University (AR)',
            'John Carroll University (OH)',
            'John F. Kennedy University (CA)',
            'John Marshall Law School (IL)',
            'Johns Hopkins University (MD)',
            'Johnson University (TN)',
            'Johnson University Florida (FL)',
            'Johnson C. Smith University (NC)',
            'Johnson State College (VT)',
            'Johnson & Wales University (RI)',
            'Jones International University (CO)',
            'Judson College (AL)',
            'Judson University (IL)',
            'The Juilliard School (NY)',
            'Juniata College (PA)',
            'Kalamazoo College (MI)',
            'Kansas City Art Institute (MO)',
            'Kansas City University of Medicine & Biosciences (MO)',
            'Kansas State University (KS)',
            'Kansas State University–Salina (KS)',
            'Kansas Wesleyan University (KS)',
            'Kaplan University (IA)',
            'Kean University (NJ)',
            'Keene State College (NH)',
            'Keiser University (FL)',
            'Kendall College (IL)',
            'Kendall College of Art & Design of Ferris State University (MI)',
            'Kennesaw State University (GA)',
            'Kenrick-Glennon Seminary (MO)',
            'Kent State University (OH)',
            'Kent State University–Ashtabula Campus (OH)',
            'Kent State University–College of Podiatric Medicine (OH)',
            'Kent State University–Columbiana County (OH)',
            'Kent State University–Geauga (OH)',
            'Kent State University–Stark (OH)',
            'Kent State University–Trumbull Campus (OH)',
            'Kent State University–Tuscarawas (OH)',
            'Kentucky Christian University (KY)',
            'Kentucky Mountain Bible College (KY)',
            'Kentucky State University (KY)',
            'Kentucky Wesleyan College (KY)',
            'Kenyon College (OH)',
            'Kettering College (OH)',
            'Kettering University (MI)',
            'Keuka College (NY)',
            'Keystone College (PA)',
            'King University (TN)',
            'Kings College (PA)',
            'The Kings College (NY)',
            'Knowledge Systems Institute (IL)',
            'Knox College (IL)',
            'Kutztown University of Pennsylvania (PA)',
            'Kuyper College (MI)',
            'La Roche College (PA)',
            'La Salle University (PA)',
            'La Sierra University (CA)',
            'Labouré College (MA)',
            'Lafayette College (PA)',
            'LaGrange College (GA)',
            'Laguna College of Art & Design (CA)',
            'Lake Erie College (OH)',
            'Lake Erie College of Osteopathic Medicine (PA)',
            'Lake Forest College (IL)',
            'Lake Forest Graduate School of Management (IL)',
            'Lake Superior State University (MI)',
            'Lake-Sumter State College (FL)',
            'Lakeland College (WI)',
            'Lakeview College of Nursing (IL)',
            'Lamar University (TX)',
            'Lancaster Bible College (PA)',
            'Lancaster Theological Seminary (PA)',
            'Lander University (SC)',
            'Landmark College (VT)',
            'Lane College (TN)',
            'Langston University (OK)',
            'Lasell College (MA)',
            'Lawrence Technological University (MI)',
            'Lawrence University (WI)',
            'Le Moyne College (NY)',
            'Lebanon Valley College (PA)',
            'Lee University (TN)',
            'Lees-McRae College (NC)',
            'Lehigh University (PA)',
            'LeMoyne-Owen College (TN)',
            'Lenoir-Rhyne University (NC)',
            'Lesley University (MA)',
            'LeTourneau University (TX)',
            'Lewis & Clark College (OR)',
            'Lewis-Clark State College (ID)',
            'Lewis University (IL)',
            'Lexington College (IL) (closed May 2014)',
            'Liberty University (VA)',
            'Life Pacific College (CA)',
            'Life University (GA)',
            'LIM College (NY)',
            'Limestone College (SC)',
            'Lincoln Christian University (IL)',
            'Lincoln College (IL)',
            'Lincoln College of New England (CT)',
            'Lincoln Memorial University (TN)',
            'Lincoln University (MO)',
            'Lincoln University (PA)',
            'Lindenwood University (MO)',
            'Lindsey Wilson College (KY)',
            'Linfield College (OR)',
            'Lipscomb University (TN)',
            'Livingstone College (NC)',
            'Lock Haven University of Pennsylvania (PA)',
            'Logan University (MO)',
            'Loma Linda University (CA)',
            'Long Island University (NY)',
            'Long Island University–Arnold & Marie Schwartz College of Pharmacy & Health Sciences',
            'Long Island University–Brentwood Campus',
            'Long Island University–Brooklyn Campus',
            'Long Island University–C.W. Post Campus',
            'Long Island University–Hudson',
            'Long Island University–Riverhead',
            'Longwood University (VA)',
            'Longy School of Music of Bard College (MA)',
            'Loras College (IA)',
            'Louisiana College (LA)',
            'Louisiana State University (LA)',
            'Louisiana State University–Alexandria (LA)',
            'Louisiana State University–Law Center',
            'Louisiana State University Health Sciences Center–New Orleans (LA)',
            'Louisiana State University Health Sciences Center–Shreveport',
            'Louisiana State University–Shreveport (LA)',
            'Louisiana State University System (LA)',
            'Louisiana Tech University (LA)',
            'Louisville Presbyterian Theological Seminary (KY)',
            'Lourdes University (OH)',
            'Loyola University Maryland (MD)',
            'Loyola Marymount University (CA)',
            'Loyola University Chicago (IL)',
            'Loyola University New Orleans (LA)',
            'Lubbock Christian University (TX)',
            'Luther College (IA)',
            'Luther Seminary (MN)',
            'Lutheran School of Theology at Chicago (IL)',
            'Lutheran Theological Seminary at Gettysburg (PA)',
            'Lutheran Theological Seminary at Philadelphia (PA)',
            'Lycoming College (PA)',
            'Lyme Academy College of Fine Arts (CT)',
            'Lynchburg College (VA)',
            'Lyndon State College (VT)',
            'Lynn University (FL)',
            'Lyon College (AR)',
            'Macalester College (MN)',
            'MacMurray College (IL)',
            'Madonna University (MI)',
            'Maharishi University of Management (IA)',
            'Maine College of Art (ME)',
            'Maine Maritime Academy (ME)',
            'Malone University (OH)',
            'Manchester University (IN)',
            'Manhattan Christian College (KS)',
            'Manhattan College (NY)',
            'Manhattan School of Music (NY)',
            'Manhattanville College (NY)',
            'Mansfield University of Pennsylvania (PA)',
            'Maranatha Baptist University (WI)',
            'Maria College (NY)',
            'Marian University (IN)',
            'Marian University (WI)',
            'Marietta College (OH)',
            'Marine Corps University (VA)',
            'Marist College (NY)',
            'Marlboro College (VT)',
            'Marquette University (WI)',
            'Mars Hill University (NC)',
            'Marshall B. Ketchum University (CA)',
            'Marshall University (WV)',
            'Martin Luther College (MN)',
            'Martin Methodist College (TN)',
            'Martin University (IN)',
            'Mary Baldwin College (VA)',
            'Marygrove College (MI)',
            'Maryland Institute College of Art (MD)',
            'Maryland University of Integrative Health (MD)',
            'Marylhurst University (OR)',
            'Marymount California University (CA)',
            'Marymount Manhattan College (NY)',
            'Marymount University (VA)',
            'Maryville College (TN)',
            'Maryville University of Saint Louis (MO)',
            'Marywood University (PA)',
            'Massachusetts College of Art & Design (MA)',
            'Massachusetts College of Liberal Arts (MA)',
            'Massachusetts College of Pharmacy & Health Sciences (MA)',
            'Massachusetts Institute of Technology (MA)',
            'Massachusetts Maritime Academy (MA)',
            'Massachusetts School of Law (MA)',
            'The Masters College (CA)',
            'The Masters Seminary (CA)',
            'Maui College (HI)',
            'Mayo Clinic College of Medicine (MN)',
            'Mayo Clinic College of Medicine–Graduate School',
            'Mayo Clinic College of Medicine–Medical School',
            'Mayo Clinic College of Medicine–School of Health Sciences',
            'Mayville State University (ND)',
            'McCormick Theological Seminary (IL)',
            'McDaniel College (MD)',
            'McKendree University (IL)',
            'McMurry University (TX)',
            'McNeese State University (LA)',
            'McPherson College (KS)',
            'Medaille College (NY)',
            'Medical College of Wisconsin (WI)',
            'Medical University of South Carolina (SC)',
            'Meharry Medical College (TN)',
            'Memphis College of Art (TN)',
            'Memphis Theological Seminary (TN)',
            'Menlo College (CA)',
            'Mercer University (GA)',
            'Mercy College (NY)',
            'Mercy College of Health Sciences (IA)',
            'Mercy College of Northwest Ohio (OH)',
            'Mercyhurst University (PA)',
            'Meredith College (NC)',
            'Merrimack College (MA)',
            'Messiah College (PA)',
            'Methodist College (IL)',
            'Methodist Theological School in Ohio (OH)',
            'Methodist University (NC)',
            'Metropolitan College of New York (NY)',
            'Metropolitan State University (MN)',
            'Metropolitan State University of Denver (CO)',
            'MGH Institute of Health Professions (MA)',
            'Miami Dade College (FL)',
            'Miami International University of Art & Design (FL)',
            'Miami University (OH)',
            'Miami University–Regional Campuses (OH)',
            'Michigan School of Professional Psychology (MI)',
            'Michigan State University (MI)',
            'Michigan Technological University (MI)',
            'Mid-America Baptist Theological Seminary (TN)',
            'Mid-America Christian University (OK)',
            'Mid-Atlantic Christian University (NC)',
            'MidAmerica Nazarene University (KS)',
            'Mid-Continent University (KY) (closed 30 June 2014)',
            'Middle Georgia State University (GA)',
            'Middle Tennessee School of Anesthesia (TN)',
            'Middle Tennessee State University (TN)',
            'Middlebury College (VT)',
            'Midland University (NE)',
            'Midstate College (IL)',
            'Midway College (KY)',
            'Midwestern Baptist Theological Seminary (MO)',
            'Midwestern University (IL / AZ)',
            'Midwestern State University (TX)',
            'Miles College (AL)',
            'Miller College (MI)',
            'Millersville University of Pennsylvania (PA)',
            'Milligan College (TN)',
            'Millikin University (IL)',
            'Mills College (CA)',
            'Millsaps College (MS)',
            'Milwaukee Institute of Art & Design (WI)',
            'Milwaukee School of Engineering (WI)',
            'Minnesota State University–Mankato (MN)',
            'Minnesota State University–Moorhead (MN)',
            'Minot State University (ND)',
            'Minneapolis College of Art & Design (MN)',
            'Misericordia University (PA)',
            'Mississippi College (MS)',
            'Mississippi State University (MS)',
            'Mississippi University for Women (MS)',
            'Mississippi Valley State University (MS)',
            'Missouri Baptist University (MO)',
            'Missouri Southern State University (MO)',
            'Missouri State University (MO)',
            'Missouri University of Science & Technology (MO)',
            'Missouri Valley College (MO)',
            'Missouri Western State University (MO)',
            'Mitchell College (CT)',
            'Molloy College (NY)',
            'Monmouth College (IL)',
            'Monmouth University (NJ)',
            'Monroe College (NY)',
            'Montana State University (MT)',
            'Montana State University–Billings (MT)',
            'Montana State University–Northern (MT)',
            'Montana Tech of The University of Montana (MT)',
            'Montclair State University (NJ)',
            'Montreat College (NC)',
            'Montserrat College of Art (MA)',
            'Moody Bible Institute (IL)',
            'Moore College of Art & Design (PA)',
            'Moravian College (PA)',
            'Morehead State University (KY)',
            'Morehouse College (GA)',
            'Morehouse School of Medicine (GA)',
            'Morgan State University (MD)',
            'Morningside College (IA)',
            'Morris College (SC)',
            'Mount Aloysius College (PA)',
            'Mount Angel Seminary (OR)',
            'Mount Carmel College of Nursing (OH)',
            'Mount Holyoke College (MA)',
            'Mount Ida College (MA)',
            'Mount Marty College (SD)',
            'Mount Mary University (WI)',
            'Mount Mercy University (IA)',
            'Mount Saint Mary College (NY)',
            'Mount Saint Marys University (CA)',
            'Mount Saint Marys University (MD)',
            'Mount Vernon Nazarene University (OH)',
            'Mount Washington College (NH)',
            'Mountain State University (WV) (closed 01 January 2013)',
            'Muhlenberg College (PA)',
            'Multnomah University (OR)',
            'Murray State University (KY)',
            'Muskingum University (OH)',
            'Naropa University (CO)',
            'National American University (SD)',
            'National College of Natural Medicine (OR)',
            'National Defense University (DC)',
            'National Graduate School of Quality Management (MA)',
            'National Hispanic University (CA)',
            'National Intelligence University (DC)',
            'National Labor College (MD) (closed 26 April 2014)',
            'National-Louis University (IL)',
            'National University (CA)',
            'National University of Health Sciences (IL)',
            'Navajo Technical University (NM)',
            'Naval Postgraduate School (CA)',
            'Nazarene Bible College (CO)',
            'Nazareth College (NY)',
            'Nebraska Christian College (NE)',
            'Nebraska Methodist College (NE)',
            'Nebraska Wesleyan University (NE)',
            'Neumann University (PA)',
            'New College of Florida (FL)',
            'New England College (NH)',
            'New England College of Business (MA)',
            'New England College of Optometry (MA)',
            'New England Conservatory of Music (MA)',
            'New England Institute of Art (MA)',
            'New England Institute of Technology (RI)',
            'New Hope Christian College (OR)',
            'New Jersey City University (NJ)',
            'New Jersey Institute of Technology (NJ)',
            'New Mexico Highlands University (NM)',
            'New Mexico Institute of Mining & Technology (NM)',
            'New Mexico State University (NM)',
            'New Orleans Baptist Theological Seminary (LA)',
            'The New School (NY)',
            'New York Chiropractic College (NY)',
            'New York Institute of Technology (NY)',
            'New York Medical College (NY)',
            'New York University (NY)',
            'Newberry College (SC)',
            'Newbury College (MA)',
            'Newman University (KS)',
            'NewSchool of Architecture & Design (CA)',
            'Niagara University (NY)',
            'Nichols College (MA)',
            'Nicholls State University (LA)',
            'Norfolk State University (VA)',
            'North Carolina A&T State University (NC)',
            'North Carolina Central University (NC)',
            'North Carolina Wesleyan College (NC)',
            'North Central University (MN)',
            'North Central College (IL)',
            'North Carolina State University (NC)',
            'North Dakota State University (ND)',
            'North Greenville University (SC)',
            'North Park University (IL)',
            'Northcentral University (AZ)',
            'Northeast Ohio Medical University (OH)',
            'Northeastern Illinois University (IL)',
            'Northeastern Seminary at Roberts Wesleyan College (NY)',
            'Northeastern State University (OK)',
            'Northeastern State University–Broken Arrow (OK)',
            'Northeastern State University–Muskogee (OK)',
            'Northeastern University (MA)',
            'Northern Arizona University (AZ)',
            'Northern Baptist Theological Seminary (IL)',
            'Northern Illinois University (IL)',
            'Northern Kentucky University (KY)',
            'Northern Marianas College (MP)',
            'Northern Michigan University (MI)',
            'Northern New Mexico College (NM)',
            'Northern State University (SD)',
            'Northland College (WI)',
            'Northwest Christian University (OR)',
            'Northwest Florida State College (FL)',
            'Northwest Indian College (WA)',
            'Northwest Missouri State University (MO)',
            'Northwest Nazarene University (ID)',
            'Northwest University (WA)',
            'Northwestern College (IA)',
            'Northwestern Health Sciences University (MN)',
            'Northwestern Oklahoma State University (OK)',
            'Northwestern State University (LA)',
            'Northwestern University (IL)',
            'Northwood University (FL / MI / TX)',
            'Norwich University (VT)',
            'Notre Dame College (OH)',
            'Notre Dame of Maryland University (MD)',
            'Notre Dame de Namur University (CA)',
            'Notre Dame Seminary (LA)',
            'Nova Southeastern University (FL)',
            'Nyack College (NY)',
            'Oak Hills Christian College (MN)',
            'Oakland City University (IN)',
            'Oakland University (MI)',
            'Oakwood University (AL)',
            'Oberlin College (OH)',
            'Oblate School of Theology (TX)',
            'Occidental College (CA)',
            'Oglala Lakota College (SD)',
            'Oglethorpe University (GA)',
            'Ohio Christian University (OH)',
            'Ohio Dominican University (OH)',
            'Ohio Northern University (OH)',
            'Ohio State University (OH)',
            'Ohio State University–Lima (OH)',
            'Ohio State University–Mansfield (OH)',
            'Ohio State University–Marion (OH)',
            'Ohio State University–Newark (OH)',
            'Ohio University (OH)',
            'Ohio University–Eastern Campus',
            'Ohio University–Lancaster',
            'Ohio University–Zanesville (OH)',
            'Ohio Valley University (WV)',
            'Ohio Wesleyan University (OH)',
            'Oklahoma Baptist University (OK)',
            'Oklahoma Christian University (OK)',
            'Oklahoma City University (OK)',
            'Oklahoma Panhandle State University (OK)',
            'Oklahoma State University (OK)',
            'Oklahoma State University–Center for Health Sciences (OK)',
            'Oklahoma State University–Institute of Technology (OK)',
            'Oklahoma State University–Oklahoma City (OK)',
            'Oklahoma State University–Tulsa (OK)',
            'Oklahoma Wesleyan University (OK)',
            'Old Dominion University (VA)',
            'Olivet College (MI)',
            'Olivet Nazarene University (IL)',
            'Olivet University (CA)',
            'Olympic College (WA)',
            'Oral Roberts University (OK)',
            'Oregon College of Art & Craft (OR)',
            'Oregon Health & Science University (OR)',
            'Oregon Institute of Technology (OR)',
            'Oregon State University (OR)',
            'Otis College of Art & Design (CA)',
            'Ottawa University (KS)',
            'Otterbein University (OH)',
            'Ouachita Baptist University (AR)',
            'Our Lady of Holy Cross College (LA)',
            'Our Lady of the Lake College (LA)',
            'Our Lady of the Lake University (TX)',
            'Ozark Christian College (MO)',
            'Pace University (NY)',
            'Pacific Lutheran University (WA)',
            'Pacific Northwest College of Art (OR)',
            'Pacific Oaks College (CA)',
            'Pacific School of Religion (CA)',
            'Pacific Union College (CA)',
            'Pacific University (OR)',
            'Pacifica Graduate Institute (CA)',
            'Paine College (GA)',
            'Palm Beach Atlantic University (FL)',
            'Palm Beach State College (FL)',
            'Palmer College of Chiropractic (IA)',
            'Palo Alto University (CA)',
            'Pardee RAND Graduate School (CA)',
            'Park University (MO)',
            'Parker University (TX)',
            'Patten University (CA)',
            'Paul Quinn College (TX)',
            'Paul Smiths College (NY)',
            'Peirce College (PA)',
            'Peninsula College (WA)',
            'Penn State Law (PA)',
            'Pennsylvania College of Art & Design (PA)',
            'Pennsylvania College of Health Sciences (PA)',
            'Pennsylvania College of Technology (PA)',
            'Pennsylvania State University (PA)',
            'Pennsylvania State University–Abington (PA)',
            'Pennsylvania State University–Altoona (PA)',
            'Pennsylvania State University–Beaver (PA)',
            'Pennsylvania State University–Berks (PA)',
            'Pennsylvania State University–Brandywine (PA)',
            'Pennsylvania State University–Dickinson School of Law (PA)',
            'Pennsylvania State University–DuBois (PA)',
            'Pennsylvania State University–Erie, The Behrend College (PA)',
            'Pennsylvania State University–Fayette, The Eberly Campus (PA)',
            'Pennsylvania State University–Great Valley School of Graduate Professional Studies (PA)',
            'Pennsylvania State University–Greater Allegheny (PA)',
            'Pennsylvania State University–Harrisburg (PA)',
            'Pennsylvania State University–Hazleton (PA)',
            'Pennsylvania State University–Lehigh Valley (PA)',
            'Pennsylvania State University–Milton S. Hershey Medical Center (PA)',
            'Pennsylvania State University–Mont Alto (PA)',
            'Pennsylvania State University–New Kensington (PA)',
            'Pennsylvania State University–Schuylkill (PA)',
            'Pennsylvania State University–Shenango (PA)',
            'Pennsylvania State University–Wilkes-Barre (PA)',
            'Pennsylvania State University–Worthington Scranton (PA)',
            'Pennsylvania State University–York (PA)',
            'Pensacola State College (FL)',
            'Pentecostal Theological Seminary (TN)',
            'Pepperdine University (CA)',
            'Peru State College (NE)',
            'Pfeiffer University (NC)',
            'Philadelphia College of Osteopathic Medicine (PA)',
            'Philadelphia College of Textiles & Science (PA)',
            'Philander Smith College (AR)',
            'Phillips Graduate University (CA)',
            'Phillips Theological Seminary (OK)',
            'Phillips University (OK) (closed July 1998)',
            'Piedmont College (GA)',
            'Pillar College (NJ)',
            'Pine Manor College (MA)',
            'Pittsburg State University (KS)',
            'Pittsburgh Theological Seminary (PA)',
            'Plymouth State University (NH)',
            'Point Loma Nazarene University (CA)',
            'Point Park University (PA)',
            'Point University (GA)',
            'Polk State College (FL)',
            'Ponce Health Sciences University (PR)',
            'Pontifical College Josephinum (OH)',
            'Pontificia Universidad Católica de Puerto Rico (PR)',
            'Portland State University (OR)',
            'Post University (CT)',
            'Prairie View A&M University (TX)',
            'Pratt Institute (NY)',
            'Prescott College (AZ)',
            'Presentation College (SD)',
            'Princeton Theological Seminary (NJ)',
            'Princeton University (NJ)',
            'Principia College (IL)',
            'Presbyterian College (SC)',
            'Providence College (RI)',
            'Purdue University (IN)',
            'Purdue University–Calumet (IN)',
            'Purdue University–North Central (IN)',
            'Purdue Polytechnic Institute–Anderson (IN)',
            'Purdue Polytechnic Institute–Columbus (IN)',
            'Purdue Polytechnic Institute–Kokomo (IN)',
            'Purdue Polytechnic Institute–Lafayette (IN)',
            'Purdue Polytechnic Institute–New Albany (IN)',
            'Purdue Polytechnic Institute–Richmond (IN)',
            'Purdue Polytechnic Institute–South Bend (IN)',
            'Purdue Polytechnic Institute–Vincennes',
            'Queens University of Charlotte (NC)',
            'Quincy University (IL)',
            'Quinnipiac University (CT)',
            'Radford University (VA)',
            'Ramapo College of New Jersey (NJ)',
            'Randolph College (VA)',
            'Randolph-Macon College (VA)',
            'Ranken Technical College (MO)',
            'Rasmussen College (FL / IL / MN / ND / WI)',
            'Reconstructionist Rabbinical College (PA)',
            'Reed College (OR)',
            'Reformed Theological Seminary (MS)',
            'Regent University (VA)',
            'Regis College (MA)',
            'Regis University (CO)',
            'Reinhardt University (GA)',
            'Rensselaer Polytechnic Institute (NY)',
            'Research College of Nursing (MO)',
            'Resurrection University (IL)',
            'Rhode Island College (RI)',
            'Rhode Island School of Design (RI)',
            'Rhodes College (TN)',
            'Rice University (TX)',
            'Richmont Graduate University (TN)',
            'Rider University (NJ)',
            'Ringling College of Art & Design (FL)',
            'Ripon College (WI)',
            'Rivier University (NH)',
            'Roanoke College (VA)',
            'Robert Morris University (PA)',
            'Robert Morris University Illinois (IL)',
            'Roberts Wesleyan College (NY)',
            'Rochester College (MI)',
            'Rochester Institute of Technology (NY)',
            'Rockford University (IL)',
            'Rockhurst University (MO)',
            'Rocky Mountain College (MT)',
            'Rocky Mountain College of Art & Design (CO)',
            'Roger Williams University (RI)',
            'Rogers State University (OK)',
            'Rollins College (FL)',
            'Roosevelt University (IL)',
            'Rosalind Franklin University of Medicine & Science (IL)',
            'Rose-Hulman Institute of Technology (IN)',
            'Roseman University of Health Sciences (AZ)',
            'Rosemont College (PA)',
            'Rowan University (NJ)',
            'Rush University (IL)',
            'Rust College (MS)',
            'Rutgers University–Camden (NJ)',
            'Rutgers University–New Brunswick (NJ)',
            'Rutgers University–Newark (NJ)',
            'Sacred Heart Major Seminary (MI)',
            'Sacred Heart Seminary & School of Theology (WI)',
            'Sacred Heart University (CT)',
            'The Sage Colleges (NY)',
            'Saginaw Valley State University (MI)',
            'Saint Ambrose University (IA)',
            'Saint Andrews University (NC)',
            'Saint Anselm College (NH)',
            'Saint Anthony College of Nursing (IL)',
            'Saint Augustine College (IL)',
            'Saint Augustines University (NC)',
            'Saint Bonaventure University (NY)',
            'Saint Catherine University (MN)',
            'Saint Catharine College (KY)',
            'Saint Charles Borromeo Seminary (PA)',
            'Saint Cloud State University (MN)',
            'Saint Edwards University (TX)',
            'Saint Francis College (NY)',
            'Saint Francis Medical Center College of Nursing (IL)',
            'Saint Francis University (PA)',
            'Saint Gregory the Great Seminary (NE)',
            'Saint Gregorys University (OK)',
            'Saint John Fisher College (NY)',
            'Saint John Vianney College Seminary (FL)',
            'Saint Johns College–Annapolis (MD & NM)',
            'Saint Johns College (IL)',
            'Saint Johns Seminary (CA)',
            'Saint Johns Seminary (MA)',
            'Saint Johns University & College of Saint Benedict (MN)',
            'Saint Johns University (NY)',
            'Saint Johns River State College (FL)',
            'Saint Joseph Seminary College (LA)',
            'Saint Josephs College (IN)',
            'Saint Josephs College (NY)',
            'Saint Josephs College of Maine (ME)',
            'Saint Josephs Seminary (NY)',
            'Saint Josephs University (PA)',
            'Saint Lawrence University (NY)',
            'Saint Leo University (FL)',
            'Saint Louis College of Pharmacy (MO)',
            'Saint Louis University (MO)',
            'Saint Lukes College (IA)',
            'Saint Lukes College of Health Sciences (MO)',
            'Saint Martins University (WA)',
            'Saint Mary Seminary & Graduate School of Theology (OH)',
            'Saint Mary-of-the-Woods College (IN)',
            'Saint Marys College (IN)',
            'Saint Marys College of California (CA)',
            'Saint Marys College of Maryland (MD)',
            'Saint Marys Seminary & University (MD)',
            'Saint Marys University of Minnesota (MN)',
            'Saint Marys University (TX)',
            'Saint Meinrad Seminary & School of Theology (IN)',
            'Saint Michaels College (VT)',
            'Saint Norbert College (WI)',
            'Saint Olaf College (MN)',
            'Saint Patricks Seminary & University (CA)',
            'Saint Paul School of Theology (MO)',
            'Saint Peters University (NJ)',
            'Saint Petersburg College (FL)',
            'Saint Thomas Aquinas College (NY)',
            'Saint Thomas University (FL)',
            'Saint Vincent College (PA)',
            'Saint Vincent de Paul Regional Seminary (FL)',
            'Saint Vincents College (CT)',
            'Saint Xavier University (IL)',
            'Salem College (NC)',
            'Salem International University (WV)',
            'Salem State University (MA)',
            'Salisbury University (MD)',
            'Salish Kootenai College (MT)',
            'Salus University (PA)',
            'Salve Regina University (RI)',
            'Sam Houston State University (TX)',
            'Samford University (AL)',
            'Samuel Merritt University (CA)',
            'San Diego Christian College (CA)',
            'San Diego State University (CA)',
            'San Francisco Art Institute (CA)',
            'San Francisco Conservatory of Music (CA)',
            'San Francisco State University (CA)',
            'San Francisco Theological Seminary (CA)',
            'San Joaquin College of Law (CA)',
            'San José State University (CA)',
            'San Juan Bautista School of Medicine (PR)',
            'Santa Clara University (CA)',
            'Santa Fe College (FL)',
            'Santa Fe University of Art & Design (NM)',
            'Sarah Lawrence College (NY)',
            'Savannah College of Art & Design (GA)',
            'Savannah State University (GA)',
            'Saybrook University (CA)',
            'School for International Training (VT)',
            'School of the Art Institute of Chicago (IL)',
            'School of Visual Arts (NY)',
            'Schreiner University (TX)',
            'Scripps Research Institute (CA)',
            'Seattle Pacific University (WA)',
            'Seattle University (WA)',
            'Seminario Evangélico de Puerto Rico (PR)',
            'Seminary of the Immaculate Conception (NY)',
            'Seminary of the Southwest (TX)',
            'Seminole State College of Florida (FL)',
            'Seton Hall University (NJ)',
            'Seton Hill University (PA)',
            'Shaw University (NC)',
            'Shawnee State University (OH)',
            'Shenandoah University (VA)',
            'Shepherd University (WV)',
            'Sherman College of Chiropractic (SC)',
            'Shimer College (IL)',
            'Shippensburg University of Pennsylvania (PA)',
            'Shorter University (GA)',
            'Siena College (NY)',
            'Siena Heights University (MI)',
            'Sierra Nevada College (NV)',
            'Silver Lake College (WI)',
            'Simmons College (MA)',
            'Sinte Gleska University (SD)',
            'Simpson University (CA)',
            'Simpson College (IA)',
            'Sioux Falls Seminary (SD)',
            'Sistema Universitario Ana G. Méndez (PR)',
            'Sitting Bull College (ND)',
            'Skidmore College (NY)',
            'Slippery Rock University of Pennsylvania (PA)',
            'Smith College (MA)',
            'Sofia University (CA)',
            'Soka University of America (CA)',
            'Sonoma State University (CA)',
            'South Carolina State University (SC)',
            'South College (TN)',
            'South Dakota School of Mines & Technology (SD)',
            'South Dakota State University (SD)',
            'South Florida Bible College & Theological Seminary (FL)',
            'South Florida State College (FL)',
            'South Georgia State College (GA)',
            'South Texas College of Law (TX)',
            'South University (GA)',
            'Southeast Missouri State University (MO)',
            'Southeastern Baptist Theological Seminary (NC)',
            'Southeastern Bible College (AL)',
            'Southeastern University (FL)',
            'Southeastern Louisiana University (LA)',
            'Southeastern Oklahoma State University (OK)',
            'Southern Adventist University (TN)',
            'Southern Arkansas University (AR)',
            'Southern Baptist Theological Seminary (KY)',
            'Southern California Institute of Architecture (CA)',
            'Southern California University of Health Sciences (CA)',
            'Southern College of Optometry (TN)',
            'Southern Connecticut State University (CT)',
            'Southern Illinois University–Carbondale (IL)',
            'Southern Illinois University–Edwardsville (IL)',
            'Southern Methodist University (TX)',
            'Southern Nazarene University (OK)',
            'Southern New Hampshire University (NH)',
            'Southern Oregon University (OR)',
            'Southern University and A&M College at Baton Rouge (LA)',
            'Southern University at New Orleans (LA)',
            'Southern University at Shreveport (LA)',
            'Southern University System (LA)',
            'Southern Utah University (UT)',
            'Southern Vermont College (VT)',
            'Southern Virginia University (VA)',
            'Southern Wesleyan University (SC)',
            'Southwest Baptist University (MO)',
            'Southwest College of Naturopathic Medicine & Health Sciences (AZ)',
            'Southwest Minnesota State University (MN)',
            'Southwest University of Visual Arts (AZ)',
            'Southwestern Adventist University (TX)',
            'Southwestern Assemblies of God University (TX)',
            'Southwestern Baptist Theological Seminary (TX)',
            'Southwestern Christian College (TX)',
            'Southwestern Christian University (OK)',
            'Southwestern College (KS)',
            'Southwestern College (NM)',
            'Southwestern Oklahoma State University (OK)',
            'Southwestern University (TX)',
            'Spalding University (KY)',
            'Spelman College (GA)',
            'Spertus Institute for Jewish Learning & Leadership (IL)',
            'Spring Arbor University (MI)',
            'Spring Hill College (AL)',
            'Springfield College (MA)',
            'Stanford University (CA)',
            'State College of Florida, Manatee-Sarasota (FL)',
            'State University of New York System (NY)',
            'Stephen F. Austin State University (TX)',
            'Stephens College (MO)',
            'Sterling College (KS)',
            'Sterling College (VT)',
            'Stetson University (FL)',
            'Stevens Institute of Technology (NJ)',
            'Stevenson University (MD)',
            'Stillman College (AL)',
            'Stockton University (NJ)',
            'Stonehill College (MA)',
            'Strayer University (DC)',
            'Suffolk University (MA)',
            'Sul Ross State University (TX)',
            'Sullivan University (KY)',
            'Summit University (PA)',
            'Susquehanna University (PA)',
            'Swarthmore College (PA)',
            'Sweet Briar College (VA)',
            'Syracuse University (NY)',
            'Tabor College (KS)',
            'Talladega College (AL)',
            'Tarleton State University (TX)',
            'Taylor University (IN)',
            'TCM International Institute (IN)',
            'Temple University (PA)',
            'Tennessee State University (TN)',
            'Tennessee Technological University (TN)',
            'Tennessee Wesleyan College (TN)',
            'Texas A&M International University (TX)',
            'Texas A&M University (TX)',
            'Texas A&M University–Central Texas (TX)',
            'Texas A&M University–Commerce (TX)',
            'Texas A&M University–Corpus Christi (TX)',
            'Texas A&M University–Galveston (TX)',
            'Texas A&M University Health Science Center (TX)',
            'Texas A&M University–Kingsville (TX)',
            'Texas A&M University–San Antonio (TX)',
            'Texas A&M University–Texarkana (TX)',
            'Texas Chiropractic College (TX)',
            'Texas Christian University (TX)',
            'Texas College (TX)',
            'Texas Lutheran University (TX)',
            'Texas Southern University (TX)',
            'Texas State University–San Marcos (TX)',
            'Texas Tech University (TX)',
            'Texas Tech University Health Sciences Center (TX)',
            'Texas Wesleyan University (TX)',
            'Texas Womans University (TX)',
            'Thiel College (PA)',
            'Thomas Aquinas College (CA)',
            'Thomas University (GA)',
            'Thomas College (ME)',
            'Thomas Edison State College (NJ)',
            'Thomas Jefferson University (PA)',
            'Thomas M. Cooley Law School (MI)',
            'Thomas More College (KY)',
            'The Thomas More College of Liberal Arts (NH)',
            'Thunderbird School of Global Management (AZ)',
            'Tiffin University (OH)',
            'Toccoa Falls College (GA)',
            'Tougaloo College (MS)',
            'Touro College (NY)',
            'Touro College Los Angeles (CA)',
            'Touro University California (CA)',
            'Touro University Nevada (NV)',
            'Touro University Worldwide (CA)',
            'Towson University (MD)',
            'Toyota Technological Institute at Chicago (IL)',
            'Transylvania University (KY)',
            'Trevecca Nazarene University (TN)',
            'Trident University International (CA)',
            'Trine University (IN)',
            'Trinity Bible College (ND)',
            'Trinity Christian College (IL)',
            'Trinity College (CT)',
            'Trinity College of Nursing & Health Sciences (IL)',
            'Trinity Lutheran Seminary (OH)',
            'Trinity Washington University (DC)',
            'Trinity College of Florida (FL)',
            'Trinity International University (IL)',
            'Trinity Lutheran College (WA)',
            'Trinity University (TX)',
            'Troy University (AL)',
            'Truett-McConnell College (GA)',
            'Truman State University (MO)',
            'Tufts University (MA)',
            'Tulane University (LA)',
            'Turtle Mountain Community College (ND)',
            'Tusculum College (TN)',
            'Tuskegee University (AL)',
            'Unification Theological Seminary (NY)',
            'Uniformed Services University of the Health Sciences (MD)',
            'Union College (KY)',
            'Union College (NE)',
            'Union College (NY)',
            'Union Graduate College (NY)',
            'Union Institute & University (OH)',
            'Union Presbyterian Seminary (VA)',
            'Union Theological Seminary (NY)',
            'Union University (TN)',
            'United States Air Force Academy (CO)',
            'United States Army Command & General Staff College (KS)',
            'United States Army War College (PA)',
            'United States Coast Guard Academy (CT)',
            'United States Merchant Marine Academy (NY)',
            'United States Military Academy (NY)',
            'United States Naval Academy (MD)',
            'United States Naval War College (RI)',
            'United States Sports Academy (AL)',
            'United States University (CA)',
            'United Theological Seminary (OH)',
            'United Theological Seminary of the Twin Cities (MN)',
            'Unity College (ME)',
            'Universidad Adventista de las Antillas (PR)',
            'Universidad Central de Bayamón (PR)',
            'Universidad Central del Caribe (PR)',
            'Universidad del Sagrado Corazón (PR)',
            'Universidad Interamericana de Puerto Rico (PR)',
            'Universidad Politecnica de Puerto Rico (PR)',
            'University System of Maryland (MD)',
            'Upper Iowa University (IA)',
            'Urbana University (OH)',
            'Ursinus College (PA)',
            'Ursuline College (OH)',
            'Utah State University (UT)',
            'Utah Valley University (UT)',
            'Utica College (NY)',
            'University of Advancing Technology (AZ)',
            'University of Akron (OH)',
            'University of Alabama (AL)',
            'University of Alabama–Birmingham (AL)',
            'University of Alabama–Huntsville (AL)',
            'University of Alaska System (AK)',
            'University of Arizona (AZ)',
            'University of Arkansas (AR)',
            'University of Arkansas–Fort Smith (AR)',
            'University of Arkansas–Little Rock (AR)',
            'University of Arkansas for Medical Sciences (AR)',
            'University of Arkansas–Monticello (AR)',
            'University of Arkansas–Pine Bluff (AR)',
            'University of Arkansas System (AR)',
            'University of Baltimore (MD)',
            'University of Bridgeport (CT)',
            'University of California–Berkeley (CA)',
            'University of California–Davis (CA)',
            'University of California Hastings College of the Law (CA)',
            'University of California–Irvine (CA)',
            'University of California–Los Angeles (CA)',
            'University of California–Merced (CA)',
            'University of California–Riverside (CA)',
            'University of California–San Diego (CA)',
            'University of California–San Francisco (CA)',
            'University of California–Santa Barbara (CA)',
            'University of California–Santa Cruz (CA)',
            'University of California System (CA)',
            'University of Central Arkansas (AR)',
            'University of Central Florida (FL)',
            'University of Central Missouri (MO)',
            'University of Central Oklahoma (OK)',
            'University of Charleston (WV)',
            'University of Chicago (IL)',
            'University of Cincinnati (OH)',
            'University of Cincinnati–Blue Ash (OH)',
            'University of Colorado–Boulder (CO)',
            'University of Colorado–Colorado Springs (CO)',
            'University of Colorado–Denver (CO)',
            'University of Colorado System (CO)',
            'University of Connecticut (CT)',
            'University of Dallas (TX)',
            'University of Dayton (OH)',
            'University of Delaware (DE)',
            'University of Denver (CO)',
            'University of the District of Columbia (DC)',
            'University of Detroit Mercy (MI)',
            'University of Dubuque (IA)',
            'University of Evansville (IN)',
            'The University of Findlay (OH)',
            'University of Florida (FL)',
            'University of Georgia (GA)',
            'University of Great Falls (MT)',
            'University of Guam (GU)',
            'University of Hartford (CT)',
            'University of Hawaii–Hilo (HI)',
            'University of Hawaii–Manoa (HI)',
            'University of Hawaii System (HI)',
            'University of Hawaii–West Oahu (HI)',
            'University of Houston (TX)',
            'University of Houston–Clear Lake (TX)',
            'University of Houston–Downtown (TX)',
            'University of Houston–Victoria (TX)',
            'University of Idaho (ID)',
            'University of Illinois–Chicago (IL)',
            'University of Illinois–Springfield (IL)',
            'University of Illinois System (IL)',
            'University of Illinois–Urbana-Champaign (IL)',
            'University of Indianapolis (IN)',
            'University of Iowa (IA)',
            'University of Jamestown (ND)',
            'University of Kansas (KS)',
            'University of Kansas Medical Center (KS)',
            'University of Kentucky (KY)',
            'University of La Verne (CA)',
            'University of Louisiana–Monroe (LA)',
            'University of Louisiana–Lafayette (LA)',
            'University of Louisville (KY)',
            'University of Maine (ME)',
            'University of Maine–Augusta (ME)',
            'University of Maine–Farmington (ME)',
            'University of Maine–Fort Kent (ME)',
            'University of Maine–Machias (ME)',
            'University of Maine–Presque Isle (ME)',
            'University of Maine School of Law (ME)',
            'University of Maine System (ME)',
            'University of Mary (ND)',
            'University of Mary Hardin-Baylor (TX)',
            'University of Mary Washington (VA)',
            'University of Maryland–Baltimore',
            'University of Maryland–Baltimore County',
            'University of Maryland–College Park',
            'University of Maryland–Eastern Shore',
            'University of Maryland–University College',
            'University of Massachusetts–Amherst (MA)',
            'University of Massachusetts–Boston (MA)',
            'University of Massachusetts–Dartmouth (MA)',
            'University of Massachusetts–Lowell (MA)',
            'University of Massachusetts Medical School at Worcester (MA)',
            'University of Massachusetts System (MA)',
            'University of Medicine & Dentistry of New Jersey (NJ)',
            'University of Memphis (TN)',
            'University of Miami (FL)',
            'University of Michigan (MI)',
            'University of Michigan–Dearborn (MI)',
            'University of Michigan–Flint (MI)',
            'University of Minnesota–Crookston (MN)',
            'University of Minnesota–Duluth (MN)',
            'University of Minnesota–Morris (MN)',
            'University of Minnesota–Rochester (MN)',
            'University of Minnesota–Twin Cities (MN)',
            'University of Mississippi (MS)',
            'University of Mississippi Medical Center (MS)',
            'University of Missouri (MO)',
            'University of Missouri–Kansas City (MO)',
            'University of Missouri–Saint Louis (MO)',
            'University of Missouri System (MO)',
            'University of Mobile (AL)',
            'University of Montana–Missoula (MT)',
            'University of Montana–Western (MT)',
            'University of Montevallo (AL)',
            'University of Mount Olive (NC)',
            'University of Mount Union (OH)',
            'University of Nebraska–Kearney (NE)',
            'University of Nebraska–Lincoln (NE)',
            'University of Nebraska Medical Center (NE)',
            'University of Nebraska–Omaha (NE)',
            'University of Nebraska System (NE)',
            'University of Nevada–Las Vegas (NV)',
            'University of Nevada–Reno (NV)',
            'University of New England (ME)',
            'University of New Hampshire (NH)',
            'University of New Hampshire at Manchester (NH)',
            'University of New Hampshire School of Law (NH)',
            'University of New Haven (CT)',
            'University of New Mexico (NM)',
            'University of New Orleans (LA)',
            'University of North Alabama (AL)',
            'University of North Carolina–Asheville (NC)',
            'University of North Carolina–Chapel Hill (NC)',
            'University of North Carolina–Charlotte (NC)',
            'University of North Carolina–Greensboro (NC)',
            'University of North Carolina–Pembroke (NC)',
            'University of North Carolina–School of the Arts (NC)',
            'University of North Carolina–Wilmington (NC)',
            'University of North Dakota (ND)',
            'University of North Florida (FL)',
            'University of North Georgia (GA)',
            'University of North Texas (TX)',
            'University of North Texas–Dallas (TX)',
            'University of North Texas Health Science Center (TX)',
            'University of Northern Colorado (CO)',
            'University of Northern Iowa (IA)',
            'University of Northwestern Ohio (OH)',
            'University of Northwestern–Saint Paul (MN)',
            'University of Notre Dame (IN)',
            'University of Oklahoma (OK)',
            'University of Oklahoma Health Sciences Center (OK)',
            'University of Oklahoma–Tulsa (OK)',
            'University of Oregon (OR)',
            'University of the Ozarks (AR)',
            'University of the Pacific (CA)',
            'University of Pennsylvania (PA)',
            'University of Phoenix (AZ)',
            'University of Pikeville (KY)',
            'University of Pittsburgh (PA)',
            'University of Pittsburgh–Bradford (PA)',
            'University of Pittsburgh–Greensburg (PA)',
            'University of Pittsburgh–Johnstown (PA)',
            'University of Portland (OR)',
            'University of the Potomac (DC)',
            'University of Puerto Rico–Aguadilla (PR)',
            'University of Puerto Rico–Arecibo (PR)',
            'University of Puerto Rico–Bayamón (PR)',
            'University of Puerto Rico–Carolina (PR)',
            'University of Puerto Rico–Cayey (PR)',
            'University of Puerto Rico–Ciencias Médicas (PR)',
            'University of Puerto Rico–Humacao (PR)',
            'University of Puerto Rico–Mayagüez (PR)',
            'University of Puerto Rico–Ponce (PR)',
            'University of Puerto Rico–Río Piedras (PR)',
            'University of Puerto Rico System (PR)',
            'University of Puerto Rico–Utuado (PR)',
            'University of Puget Sound (WA)',
            'University of Redlands (CA)',
            'University of Rhode Island (RI)',
            'University of Richmond (VA)',
            'University of Rio Grande (OH)',
            'University of Rochester (NY)',
            'University of the Rockies (CO)',
            'University of Saint Francis (IL)',
            'University of Saint Francis (IN)',
            'University of Saint Joseph (CT)',
            'University of Saint Mary (KS)',
            'University of San Diego (CA)',
            'University of San Francisco (CA)',
            'University of Science & Arts of Oklahoma (OK)',
            'University of the Sciences in Philadelphia (PA)',
            'University of Scranton (PA)',
            'University of Sioux Falls (SD)',
            'University of Southern California (CA)',
            'University of Southern Maine (ME)',
            'University of South Carolina (SC)',
            'University of South Carolina–Aiken (SC)',
            'University of South Carolina–Beaufort (SC)',
            'University of South Carolina System (SC)',
            'University of South Carolina–Upstate (SC)',
            'University of South Dakota (SD)',
            'University of South Florida (FL)',
            'University of South Florida Saint Petersburg (FL)',
            'University of South Florida Sarasota–Manatee (FL)',
            'University of Southern Mississippi (MS)',
            'University of Saint Thomas (TX)',
            'University of Saint Thomas (MN)',
            'University of South Alabama (AL)',
            'University of Southern Indiana (IN)',
            'University of Tampa (FL)',
            'University of Tennessee (TN)',
            'University of Tennessee–Chattanooga (TN)',
            'University of Tennessee Health Science Center (TN)',
            'University of Tennessee–Martin (TN)',
            'University of Tennessee System (TN)',
            'University of Texas–Arlington (TX)',
            'University of Texas–Austin (TX)',
            'University of Texas–Brownsville (TX)',
            'University of Texas–Dallas (TX)',
            'University of Texas–El Paso (TX)',
            'University of Texas Health Science Center at Houston (TX)',
            'University of Texas Health Science Center at San Antonio (TX)',
            'University of Texas Health Science Center at Tyler (TX)',
            'University of Texas M.D. Anderson Cancer Center (TX)',
            'University of Texas Medical Branch at Galveston (TX)',
            'University of Texas–Pan American (TX)',
            'University of Texas of the Permian Basin (TX)',
            'University of Texas–San Antonio (TX)',
            'University of Texas Southwestern Medical Center at Dallas (TX)',
            'University of Texas System (TX)',
            'University of Texas–Tyler (TX)',
            'University of the Arts (PA)',
            'University of the Cumberlands (KY)',
            'University of the Incarnate Word (TX)',
            'University of the South (TN)',
            'University of the Southwest (NM)',
            'University of Toledo (OH)',
            'University of Tulsa (OK)',
            'University of Utah (UT)',
            'University of Valley Forge (PA)',
            'University of Vermont (VT)',
            'University of the Virgin Islands (VI)',
            'University of Virginia (VA)',
            'University of Virginias College at Wise (VA)',
            'University of Washington (WA)',
            'University of Washington–Bothell (WA)',
            'University of Washington–Tacoma (WA)',
            'University of West Alabama (AL)',
            'University of West Florida (FL)',
            'University of West Georgia (GA)',
            'University of Western States (OR)',
            'University of the West (CA)',
            'University of Wisconsin–Eau Claire (WI)',
            'University of Wisconsin–Green Bay (WI)',
            'University of Wisconsin–La Crosse (WI)',
            'University of Wisconsin–Madison (WI)',
            'University of Wisconsin–Milwaukee (WI)',
            'University of Wisconsin–Oshkosh (WI)',
            'University of Wisconsin–Parkside (WI)',
            'University of Wisconsin–Platteville (WI)',
            'University of Wisconsin–River Falls (WI)',
            'University of Wisconsin–Stevens Point (WI)',
            'University of Wisconsin–Stout (WI)',
            'University of Wisconsin–Superior (WI)',
            'University of Wisconsin System (WI)',
            'University of Wisconsin–Whitewater (WI)',
            'University of Wyoming (WY)',
            'Valdosta State University (GA)',
            'Valencia College (FL)',
            'Valley City State University (ND)',
            'Valparaiso University (IN)',
            'Vanderbilt University (TN)',
            'VanderCook College of Music (IL)',
            'Vanguard University of Southern California (CA)',
            'Vassar College (NY)',
            'Vaughn College of Aeronautics & Technology (NY)',
            'Vermont College of Fine Arts (VT)',
            'Vermont Law School (VT)',
            'Vermont Technical College (VT)',
            'Villa Maria College (NY)',
            'Villanova University (PA)',
            'Vincennes University (IN)',
            'Virginia Commonwealth University (VA)',
            'Virginia Military Institute (VA)',
            'Virginia Polytechnic Institute & State University (VA)',
            'Virginia State University (VA)',
            'Virginia Union University (VA)',
            'Virginia Wesleyan College (VA)',
            'Viterbo University (WI)',
            'Voorhees College (SC)',
            'Wabash College (IN)',
            'Wade College (TX)',
            'Wagner College (NY)',
            'Wake Forest University (NC)',
            'Walden University (MN)',
            'Waldorf College (IA)',
            'Walla Walla University (WA)',
            'Walsh College (MI)',
            'Walsh University (OH)',
            'Warner Pacific College (OR)',
            'Warner University (FL)',
            'Warren Wilson College (NC)',
            'Wartburg College (IA)',
            'Wartburg Theological Seminary (IA)',
            'Washburn University (KS)',
            'Washington & Jefferson College (PA)',
            'Washington & Lee University (VA)',
            'Washington Adventist University (MD)',
            'Washington College (MD)',
            'Washington State University (WA)',
            'Washington State University–Spokane (WA)',
            'Washington State University–Tri-Cities (WA)',
            'Washington State University–Vancouver (WA)',
            'Washington Theological Union (DC)',
            'Washington University in Saint Louis (MO)',
            'Watkins College of Art, Design, & Film (TN)',
            'Wayland Baptist University (TX)',
            'Wayne State College (NE)',
            'Wayne State University (MI)',
            'Waynesburg University (PA)',
            'Webb Institute (NY)',
            'Webber International University (FL)',
            'Weber State University (UT)',
            'Webster University (MO)',
            'Welch College (TN)',
            'Wellesley College (MA)',
            'Wells College (NY)',
            'Wentworth Institute of Technology (MA)',
            'Wesley College (DE)',
            'Wesley Theological Seminary (DC)',
            'Wesleyan College (GA)',
            'Wesleyan University (CT)',
            'West Chester University of Pennsylvania (PA)',
            'West Coast University (CA)',
            'West Liberty University (WV)',
            'West Texas A&M University (TX)',
            'West Virginia State University (WV)',
            'West Virginia University (WV)',
            'West Virginia University Institute of Technology (WV)',
            'West Virginia University at Parkersburg (WV)',
            'West Virginia Wesleyan College (WV)',
            'Western Carolina University (NC)',
            'Western Connecticut State University (CT)',
            'Western Governors University (UT)',
            'Western Governors University–Indiana (IN)',
            'Western Governors University–Missouri (MO)',
            'Western Governors University–Tennessee (TN)',
            'Western Governors University–Texas (TX)',
            'Western Governors University–Washington (WA)',
            'Western Illinois University (IL)',
            'Western International University (AZ)',
            'Western Kentucky University (KY)',
            'Western Michigan University (MI)',
            'Western Nevada College (NV)',
            'Western New England University (MA)',
            'Western New Mexico University (NM)',
            'Western Oregon University (OR)',
            'Western Seminary (OR)',
            'Western State Colorado University (CO)',
            'Western State University College of Law (CA)',
            'Western University of Health Sciences (CA)',
            'Western Washington University (WA)',
            'Westfield State University (MA)',
            'Westminster College (PA)',
            'Westminster College (MO)',
            'Westminster College (UT)',
            'Westminster Theological Seminary (PA)',
            'Westminster Seminary California (CA)',
            'Westmont College (CA)',
            'Wheaton College (IL)',
            'Wheaton College (MA)',
            'Wheeling Jesuit University (WV)',
            'Wheelock College (MA)',
            'Whitman College (WA)',
            'Whittier College (CA)',
            'Whitworth University (WA)',
            'Wichita State University (KS)',
            'Widener University (PA)',
            'Wilberforce University (OH)',
            'Wiley College (TX)',
            'Wilkes University (PA)',
            'Willamette University (OR)',
            'William Carey University (MS)',
            'William James College (MA)',
            'William Jessup University (CA)',
            'William Jewell College (MO)',
            'William Peace University (NC)',
            'William Penn University (IA)',
            'William Paterson University (NJ)',
            'William Woods University (MO)',
            'Williams Baptist College (AR)',
            'Williams College (MA)',
            'Wilmington University (DE)',
            'Wilmington College (OH)',
            'Wilson College (PA)',
            'Wingate University (NC)',
            'Winona State University (MN)',
            'Winston-Salem State University (NC)',
            'Winthrop University (SC)',
            'Wisconsin Lutheran College (WI)',
            'Wisconsin School of Professional Psychology (WI)',
            'Wittenberg University (OH)',
            'Wofford College (SC)',
            'Won Institute of Graduate Studies (PA)',
            'Woodbury University (CA)',
            'Woods Hole Oceanographic Institution (MA)',
            'Worcester Polytechnic Institute (MA)',
            'Worcester State University (MA)',
            'The Wright Institute (CA)',
            'Wright State University (OH)',
            'Xavier University (OH)',
            'Xavier University of Louisiana (LA)',
            'Yale University (CT)',
            'Yeshiva University (NY)',
            'York College (NE)',
            'York College of Pennsylvania (PA)',
            'Young Harris College (GA)',
            'Youngstown State University (OH)',
            'Zaytuna College (CA)',
        ];

        for ($i = 0; $i < count($schools); $i++) {
            University::create([
                'university' => $schools[$i]
            ]);
        }
    }
}
